--- 
#- include: RedHat.yml
 # when: ansible_os_family == 'RedHat' 
# when: ansible_distribution in [ 'Debian', 'Ubuntu' ] 
#- include: Ubuntu.yml
 # when: ansible_os_family == 'Ubuntu'
# when: ansible_distribution in [ 'CentOS' ]
- include: copy_code.yml 
